### ISSUE TITLE
New button for external url

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#44]
Hi,

What do you think of creating a new button in host's details with a drop-down list to external URLs that we would have defined in the conf?

```
external_urls: 1
external_url_lists:
  Thruk: https://www.example.com/thruk/#cgi-bin/extinfo.cgi?type=1&host={{HOSTNAME}}
  Other: ...
```
