### ISSUE TITLE
All monitoring services of certain hosts are seen in the Statusengine interface

### ISSUE THREAD

**Issue by sistemmsn** [statusengine/interface#56]
hi how are things 

from the Statusengine interface it only shows me 15 monitored services and in nagios oh thruk it shows me 17 attached evidence

interface Statusengine:
![imagen](https://user-images.githubusercontent.com/38023703/221288271-edcf8964-af31-4355-9186-2a656eba3dbf.png)

thruk:
![imagen](https://user-images.githubusercontent.com/38023703/221288319-2beee637-3a4b-44b3-94d0-86d02f8c0059.png)

I attach my configuration
/usr/share/statusengine-ui/etc/config.yml:

```yml
# Statusengine UI Configuration



allow_anonymous: 0


anonymous_can_submit_commands: 1

urls_without_login:
  - login #looks like /login in the browser's address bar
  - loginstate

auth_type: basic

use_mysql: 1


mysql:
    host: 127.0.0.1
    port: 3306
    username: statusengine
    password: x
    database: statusengine
    encoding: utf8




display_perfdata: 1

perfdata_backend: mysql
```

MySQL as Performance Data Backend WORKER:

```yml
# Statusengine Worker Configuration


node_name: Statusengine


use_gearman: 1

gearman:
  address: 127.0.0.1
  port: 4730
  timeout: 1000

use_redis: 1

redis:
  address: 127.0.0.1
  port: 6379
  db: 0

store_live_data_in_archive_backend: 1

use_mysql: 1

mysql:
    host: 127.0.0.1
    port: 3306
    username: statusengine
    password: x
    database: statusengine
    encoding: utf8

dump_mysql_query_parameters: 0

number_of_bulk_records: 100

max_bulk_delay: 2

number_servicestatus_worker: 1

number_hoststatus_worker: 1

number_logentry_worker: 1

number_statechange_worker: 1

number_hostcheck_worker: 1

number_servicecheck_worker: 1

number_misc_worker: 1

process_perfdata: 1

number_perfdata_worker: 1

 - mysql

check_for_commands: 1

command_check_interval: 15

external_command_file: /opt/nagios/var/rw/nagios.cmd

query_handler: /opt/nagios/var/rw/nagios.qh

submit_method: broker

syslog_enabled: 1

syslog_tag: statusengine-worker

age_hostchecks: 5


age_host_acknowledgements: 60


age_host_notifications: 60


age_host_statehistory: 365


age_host_downtimes: 60

age_servicechecks: 5


age_service_acknowledgements: 60


age_service_notifications: 60


age_service_statehistory: 365


age_service_downtimes: 60


age_logentries: 5


age_tasks: 1


age_perfdata: 90

disable_http_proxy: 1
```
